name: analog_clock_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_neumorphic: ^3.2.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.2.0
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  shared_preferences: ^2.0.11
  audioplayers: ^0.20.1
  rxdart: ^0.27.3
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  fluttertoast: ^8.0.8
  adaptive_dialog: ^1.2.0

# https://iconarchive.com/show/flatwoken-icons-by-alecive/Apps-Alarm-icon.html
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/